# Using ProtocolLib will use packets instead of events.
motd:
  enabled: true

  # Placeholders: %onlineplayers% %maxplayers%
  motds:
    - |- 
        &b&lCleanMoTD &f&lDefault &b&lMoTD
        &7There are &a%onlineplayers%&7 players online!
    - |-
        &aCleanMoTD Default MoTD &c[Optimized]
        &d&lCome and enjoy our brand new games!

# This is the list of message shown when hovering over the player count.
# Requires ProtocolLib, doesn't work on Bungee.
sample:
  enabled: true

  # Placeholders: %onlineplayers% %maxplayers%
  samples:
    - |-
      &b&lCleanMoTD &f&lDefault &b&lSample
      &7Online: &a%onlineplayers%&8/&a%maxplayers%
    - |-
      &aCleanMoTD Default Sample &c[Optimized]
      &d&lNew Sample feature!

# This is shown as the server version.
# Requires ProtocolLib, doesn't work on Bungee.
protocol:
  enabled: true

  # Protocol name
  name: "FlameCord 1.7-1.16.5"

maxplayers:
  enabled: true

  # Changes the max players value.
  maxplayers: 1400

  # Changes the max player value depending on your onlineplayers.
  # Example: 12/13 players online.
  justonemore: true

# Requires ProtocolLib on Bukkit.
fakeplayers:
  enabled: false

  # Sets the amount of fakeplayers.
  amount: 3

  # "STATIC": Adds the value of fakeplayers to the amount of players online.
  # "RANDOM": Adds a random amount of players between 1 and the fakeplayers value.
  # "DIVISION": Adds the amount of players online divided by the fakeplayers value.
  mode: "DIVISION"