motd:
  # Do you want to enable this module?
  enabled: true

  # Placeholders: %onlineplayers% %maxplayers%
  motds:
    - |- 
        &b&lCleanMoTD &f&lDefault &b&lMoTD
        &7There are &a%onlineplayers%&7 players online!
    - |-
        &aCleanMoTD Default MoTD &c[Optimized]
        &d&lCome and enjoy our brand new games!

# This is the list of message shown when hovering over the player count.
# Sample feature requires ProtocolLib to modify this on Spigot.
sample:
  # Do you want to enable this module?
  enabled: true

  # Placeholders: %onlineplayers% %maxplayers%
  samples:
    - |-
      &b&lCleanMoTD &f&lDefault &b&lSample
      &7Online: &a%onlineplayers%&8/&a%maxplayers%
      &5
    - |-
      &aCleanMoTD Default Sample &c[Optimized]
      &d&lNew Sample feature!
      &5

# Protocol feature requires ProtocolLib to change protocol name on Spigot.
protocol:
  # Do you want to enable this module?
  enabled: true

  # Protocol name
  name: "FlameCord 1.7-1.16.3"

# Caches requests to only send favicon to the first ping packet of a player.
# This can prevent crashes with bot attacks and improves performance.
# Only for BungeeCord as Spigot already seems to cache Favicons.
cache:
  # Do you want to enable this module?
  enabled: true

  # Time in milliseconds after cache is cleared.
  time: 30000

maxplayers:
  # Do you want to enable this module?
  enabled: true

  # Changes the max players value.
  maxplayers: 1400

  # Changes the max player value depending on your onlineplayers.
  # Example: 12/13 players online.
  justonemore: true

# Fake players feature requires ProtocolLib to modify player amount on Spigot.
fakeplayers:
  # Do you want to enable this module?
  enabled: false

  # Sets the amount of fakeplayers.
  amount: 3

  # "STATIC": Adds the value of fakeplayers to the amount of players online.
  # "RANDOM": Adds a random amount of players between 1 and the fakeplayers value.
  # "DIVISION": Adds the amount of players online divided by the fakeplayers value.
  mode: "DIVISION"