motd:
  # Do you want to enable this module?
  enabled: true

  # Placeholders: %onlineplayers% %maxplayers% %newline%
  # Use %newline% to separate lines.
  motds:
    - "&a&lWelcome to BungeeMOTD server!&r%newline%&b&lThere are %onlineplayers% players online!"
    - "&e&lThis is the first line!%newline%&c&lThis is the second line!"
    - "&d&lYou can set%newline%&5&lMultiple motds"

maxplayers:
  # Do you want to enable this module?
  enabled: true

  # Changes the max players value.
  maxplayers: 1400

  # Changes the max player value depending on your onlineplayers.
  # Example: 12/13 players online.
  justonemore: true

fakeplayers:
  # Do you want to enable this module?
  enabled: false

  # Sets the amount of fakeplayers.
  amount: 3

  # Available Modes:
  # "STATIC": Adds the value of fakeplayers to the amount of players online.
  # "RANDOM": Adds a random amount of players between 1 and the fakeplayers value.
  # "DIVISION": Adds the amount of players online divided by the fakeplayers value.
  mode: "DIVISION"