name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          # Fetch commits since last tag
          git fetch --tags
          LAST_TAG=$(git describe --tags --abbrev=0)
          COMMITS=$(git log ${LAST_TAG}..HEAD --oneline)
          
          # Generate release notes
          echo "## Changelog" > release_notes.md
          echo "" >> release_notes.md
          echo "$COMMITS" >> release_notes.md
          cat release_notes.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/libs/*.jar
          body_path: release_notes.md

      - name: Clean up
        run: rm release_notes.md
